import("//third-party/unittest/unittest.gni")
import("//llvm/utils/gn/build/libs/zstd/enable.gni")

unittest("DebugInfoMSFTests") {
  deps = [
    "//llvm/lib/DebugInfo/MSF",
    "//llvm/lib/Testing/Support",
  ]
  sources = [
    "MSFBuilderTest.cpp",
    "MSFCommonTest.cpp",
    "MappedBlockStreamTest.cpp",
  ]
  if (llvm_enable_zstd) {
    sources += [ "MSFZTest.cpp" ]
  }
}
