import("//llvm/utils/gn/build/libs/zstd/enable.gni")

static_library("MSF") {
  output_name = "LLVMDebugInfoMSF"
  deps = [ "//llvm/lib/Support" ]
  sources = [
    "MSFBuilder.cpp",
    "MSFCommon.cpp",
    "MSFError.cpp",
    "MappedBlockStream.cpp",
  ]
  if (llvm_enable_zstd) {
    sources += [ "MSFZ.cpp" ]
  }
}
